services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/db.sqlite:/app/db.sqlite
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - monitoring

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    volumes:
       - ./frontend:/app
  
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      # Provisioning config
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
       # Dashboards JSON files
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  grafana-data:
