global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastify-app: backend + database'
    scheme: https
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: /metrics/
    tls_config:
      insecure_skip_verify: true
  
  - job_name: 'prometheus: monitoring'
    scheme: https
    static_configs:
      - targets: ['nginx:9090']
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true

  - job_name: 'node-exporter: host/system'
    scheme: https
    static_configs:
      - targets: ['nginx:9101']
    tls_config:
      insecure_skip_verify: true

rule_files:
  - /etc/prometheus/prometheus-alerts.yml
