worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout 65;

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        root /usr/share/nginx/html;
        index index.html;

        # Serve React app
        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 8080 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # Metrics endpoint for Prometheus scraping
        location /metrics/ {
            proxy_pass http://backend:8000/metrics;
            proxy_http_version 1.1;
        }

        location / {
            proxy_pass http://backend:8000;
            proxy_http_version 1.1;
        }
    }

    # Prometheus
    server {
        listen 9090 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location /metrics/ {
            proxy_pass http://prometheus:9090/metrics;
            proxy_http_version 1.1;
        }

        location / {
            proxy_pass http://prometheus:9090/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # CORS headers
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type' always;

            # Handle OPTIONS preflight requests
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

        }
    }

    # # Node Exporter
    # # Prometheus exporter for hardware and OS metrics 
    # server {
    #     listen 9101 ssl;   # external port for HTTPS access
    #     server_name localhost;

    #     ssl_certificate     /etc/nginx/certs/cert.pem;
    #     ssl_certificate_key /etc/nginx/certs/key.pem;

    #     location / {
    #         proxy_pass http://node-exporter:9100/;
    #         proxy_http_version 1.1;
    #     }
    # }


    # Grafana
    server {
        listen 3001 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            proxy_pass http://grafana:3001/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Alertmanager
    server {
        listen 9093 ssl;   # External port for HTTPS
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            proxy_pass http://alertmanager:9093/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
